// Generated by https://quicktype.io

export interface InfoPagina {
  titulo?:         string;
  email?:          string;
  nombre_corto?:   string;
  pagina_Autor?: string;
  facebook?:       string;
  twitter?:        string;
  instagram?:      string;
  tublr?:          string;
  equipo_trabajo?: any[];
}

